require('user.settings')
require('user.keymappings')

---------------- Plugins ------------------
require('user.plugins')
require('user.nvim-tree')
require('user.treesitter')
require('user.telescope')
require('user.lualine')
require('user.cmp')
require('user.lsp')
require('user.autopairs')
require('user.comment')
require('user.gitsigns')
require('user.toggleterm')
require('user.sneak')
require('user.indent')
require('user.alpha')
